### ISSUE TITLE
Chrome driver only supports 83 version 

### ISSUE THREAD

**Issue by Maruti-Lavate** [MuhammadHassanRazaa/WhatsAppSender#3]
I have a chrome version 86, but the app gets crash while loading the chrome driver and says its support only 83
how to fix this?

**Comment by MuhammadHassanRazaa** [comment]
I'll look into it and will let you know

**Comment by MuhammadHassanRazaa** [comment]
Your Chrome Driver version needs to match your Chrome Browser version

- Get you Chrome Browser version, by typing chrome://version

- Download Chrome Driver version that matches you Chrome Browser version, form [this website] (https://chromedriver.chromium.org/downloads)
