### ISSUE TITLE
 'unknown error: cannot find Chrome binary'

### ISSUE THREAD

**Issue by engproali** [MuhammadHassanRazaa/WhatsAppSender#7]
Im having this error OpenQA.Selenium.WebDriverException: 'unknown error: cannot find Chrome binary' What Can i Do ?

**Comment by MuhammadHassanRazaa** [comment]
Did you download chrome driver?

**Comment by MuhammadHassanRazaa** [comment]
It shouldn’t give this error after installing chrome driver
